analytics.onpremise.enable=true
analytics.integration.enable=true
onpremise.email="ashish.jain2@rsystems.com"
onpremise.password="ECf+bMGx4oMofYHCyK4m5g\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1631236,\\"accountUuid\\"\:\\"194b5ee7-b3f5-492c-8465-cd40cf757bbd\\",\\"id\\"\:3001341,\\"name\\"\:\\"My Organization_01\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://ac-1631236.katalon.io/"
analytics.project="{\\n  \\"id\\"\: 2963055,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 2935759,\\n  \\"organizationId\\"\: 3001341,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2935759\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=true
