<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_WhatOriginUseMore</name>
   <tag></tag>
   <elementGuidId>caeaccee-5344-4667-9e08-a8a43371c0ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.nav.nav-tabs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabsContainer']/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;WhatOriginUseMore&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>64658d90-c9da-4ee9-9df4-b16d98da9cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav nav-tabs</value>
      <webElementGuid>06a9bb59-da99-44c4-acab-6625d25c76d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>a74f20e0-a7f8-43ed-9eb5-65b6c673d692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhatOriginUseMore</value>
      <webElementGuid>2865243c-12cd-4858-ac45-e453b8cf5d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsContainer&quot;)/nav[@class=&quot;nav nav-tabs&quot;]</value>
      <webElementGuid>497a5895-37f6-41a4-a288-3da1b9afe7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsContainer']/nav</value>
      <webElementGuid>c6112150-35a2-4b7c-b6c7-f15fbc7c3706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details about Lorem Ipsum'])[1]/following::nav[1]</value>
      <webElementGuid>34196f1d-a08d-4af0-a0fc-f8ec9ec656d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tabs'])[2]/following::nav[1]</value>
      <webElementGuid>d7961758-99ca-4aa8-9480-380f7578c1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::nav[1]</value>
      <webElementGuid>56e03189-0c76-489e-a5b5-cb5d2c5b65ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav</value>
      <webElementGuid>e3930cf3-2ea4-4569-a844-af06d964b118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'WhatOriginUseMore' or . = 'WhatOriginUseMore')]</value>
      <webElementGuid>388e41bd-4e81-41e6-a72f-4cd6241e1874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
