<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Permanent Address_permanentAddress</name>
   <tag></tag>
   <elementGuidId>0fe7a0f5-58d9-462c-97d5-b921276a1de3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permanentAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='permanentAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permanentAddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7cd9e24c-25d7-41ca-af69-f66c1a68c9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e216b213-3962-4f68-b9c3-dffaaf687859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f29a5760-ee52-488b-8e27-94076f3237a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanentAddress</value>
      <webElementGuid>ef90bf9f-b4bc-4347-9b50-6942c7c6ee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c7498c3-4532-4cec-bf38-ee3ea34f967e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permanentAddress&quot;)</value>
      <webElementGuid>289d4127-d31b-45ff-8c7a-b5d14bf527d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='permanentAddress']</value>
      <webElementGuid>2113e9d0-98d1-49ec-9cc2-47e52c4a97bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permanentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>e1a72d23-2f13-443e-b5ab-96db302103fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>68daa511-12d2-4525-a09d-14d2a164df3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'permanentAddress']</value>
      <webElementGuid>6174ece5-84f8-4723-9b4a-bf86158cdef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
