<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_testuser2222</name>
   <tag></tag>
   <elementGuidId>01f6e0c6-45f0-4144-92fa-3d722ea74d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userName-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='userName-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;testuser2222&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8d11fdbb-7d53-4a97-bca1-ab0eee99b1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>ca0ff1b7-1e98-46c0-a7f6-5aeb921898c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>5632fd14-8179-4a19-a6eb-98a936f5d276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>1b65862a-3e3b-4e7e-9b91-cbcd991716c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testuser2222</value>
      <webElementGuid>d9314614-f89c-43b1-a3f8-2983c16c61e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName-value&quot;)</value>
      <webElementGuid>7c4efcb8-615f-40b9-b634-826a97a7cac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='userName-value']</value>
      <webElementGuid>60e7b10a-a21d-47ae-94f7-bc7bcfeb1e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='books-wrapper']/div[3]/label[2]</value>
      <webElementGuid>96df1f1d-e4c4-466b-b78f-7df16a8307b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name :'])[1]/following::label[1]</value>
      <webElementGuid>fecf4567-4287-4c1a-8b7b-c25d4b423a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books :'])[1]/following::label[2]</value>
      <webElementGuid>5ccb7f28-e68d-45fc-b16c-e6cdb477c129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::label[1]</value>
      <webElementGuid>73291c4a-af4e-4798-b777-f3403d018b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image'])[1]/preceding::label[1]</value>
      <webElementGuid>74bfaa38-2159-471c-9615-899ce595e8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testuser2222']/parent::*</value>
      <webElementGuid>2b48518f-8b92-495e-8eab-336a5e705bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>0b90784a-7d8e-4ce8-b228-6275e295b1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = 'testuser2222' or . = 'testuser2222')]</value>
      <webElementGuid>b82a1880-69cc-4c18-8e9d-1dc687350db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
