<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click Me</name>
   <tag></tag>
   <elementGuidId>50d04d41-c68b-48cc-878d-b9b49f03f1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xZoUm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'xZoUm' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'Click Me') and starts-with(@class, 'btn btn-primary') ]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Click Me&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10b8d360-8ea7-47a3-81ee-95e2c1c374b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xZoUm</value>
      <webElementGuid>5c864be3-182f-4244-95f6-2fd06f33c35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09e7700b-1780-463c-a724-00531227d9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4eb65706-6d81-496c-a4b8-3e935e40d6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click Me</value>
      <webElementGuid>9e59effd-6c9a-4258-aece-4964a8df161c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xZoUm&quot;)</value>
      <webElementGuid>0f4e7194-af75-4d56-b991-96360e9603d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='xZoUm']</value>
      <webElementGuid>cdaf29e6-3d76-4a6c-9117-452f2b15400e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/div[3]/button</value>
      <webElementGuid>01a56c0d-7ba9-4bd7-bf21-e2f731787602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right Click Me'])[1]/following::button[1]</value>
      <webElementGuid>ee7a17f8-46d6-4bff-b35f-b569f5782602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Click Me'])[1]/following::button[2]</value>
      <webElementGuid>587d600e-5906-4cd8-a86f-0a79bf1158b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::button[1]</value>
      <webElementGuid>751db9cc-a109-4f40-9c99-d9db491aa8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click Me']/parent::*</value>
      <webElementGuid>a3f27e96-4090-43a7-80b3-b1ba92291b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>acac361c-698b-4f97-9957-caa97f06458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'xZoUm' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      <webElementGuid>b435b399-79f2-4d6f-830a-39a13199a064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SHg1c']</value>
      <webElementGuid>96d97b21-c402-4803-b9d6-1666ef90a519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'SHg1c' and @type = 'button' and (text() = 'Click Me' or . = 'Click Me')]</value>
      <webElementGuid>f519fcd2-7459-4666-bce9-9f2383231d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
